import { AppoloWrapper } from "@/providers/AppoloWrapper";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppoloWrapper>
          <h1 className="text-center mt-6 font-bold text-3xl">Book List</h1>
          {children}
        </AppoloWrapper>
      </body>
    </html>
  );
}
